name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Build type (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # Use Ubuntu 22.04 as the target OS
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true  # Ensure submodules are initialized

    - name: Set up ROS 2 Humble
      uses: ros-tooling/setup-ros@v0.9
      with:
        ros-distro: humble

    - name: Setup Qt
      uses: jurplel/install-qt-action@v2.0.0
      with:
        version: 5.15.3  # Specify Qt version
        extensions: clang_64  # Specify the Qt extension for Ubuntu

    - name: Update apt repos
      run: sudo apt-get update

    - name: Install additional dependencies
      run: |
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          python3-colcon-common-extensions  # For colcon build

    - name: Source ROS 2 setup script
      run: |
        source /opt/ros/humble/setup.bash
        echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

    - name: Build with colcon
      run: |
        colcon build --symlink-install --base-paths .
      shell: bash

    - name: Run tests
      run: |
        colcon test
        colcon test-result
      shell: bash
